name: Portfolio CD

on: [push]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr -u ${{ secrets.REGISTRY_USER }} --password-stdin
          docker build -t registry.bastian-somon.fr/portfolio:latest .
          docker push registry.bastian-somon.fr/portfolio:latest

  deploy-infra:
    needs: [ build-client ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger deploy
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -k infra/application

  rollout-infra:
    needs: [ deploy-infra ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger frontend rollout
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment nginx -n portfolio
